export const SKINS = [
  {
    id: 'standard',
    name: "평범한 3겹 데코 🧻",
    description: "부드럽고 평범한 화장지. 안전하고 무난하지만 속도가 보통입니다.",
    emoji: "😣",
    paperColor: "#ffffff",
    lineWidth: 10,
    speed: 3.6,
    unlocked: true,
  },
  {
    id: 'gold',
    name: "로열 골드 24K 👑🧻",
    description: "부의 상징 금박 화장지. 선폭이 넓어서 몬스터에게 들키기 쉽지만 왠지 모르게 튼튼하고 고급집니다.",
    emoji: "😎",
    paperColor: "#ffd700",
    lineWidth: 14,
    speed: 4.0,
    unlocked: false,
    unlockScore: 5000,
  },
  {
    id: 'pink',
    name: "딸기향 엠보싱 🌸🧻",
    description: "상큼한 향기가 나는 핑크빛 화장지. 무게가 가벼워 매우 날렵하게 이동할 수 있습니다.",
    emoji: "🤪",
    paperColor: "#ff80ab",
    lineWidth: 9,
    speed: 4.4,
    unlocked: false,
    unlockScore: 10000,
  },
  {
    id: 'newspaper',
    name: "할아버지 신문지 📰",
    description: "휴지가 없을 때 쓰던 추억의 거친 신문지. 엄청 두껍고 뻣뻣해 느리지만 뜯어지기 어려운 면이 있죠.",
    emoji: "🤠",
    paperColor: "#b0bec5",
    lineWidth: 16,
    speed: 2.8,
    unlocked: true,
  },
  {
    id: 'cyber',
    name: "사이버 네온 빔 👽⚡",
    description: "차세대 양자 전송 휴지. 매우 얇고 날렵하며 초광속으로 질주합니다. 몬스터도 자르기 힘든 굵기!",
    emoji: "👽",
    paperColor: "#00e5ff",
    lineWidth: 6,
    speed: 5.0,
    unlocked: false,
    unlockScore: 20000,
  }
];
